// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYSeJzZwCMJ3CjIMciwn03WrIqo27Gbvo',
    appId: '1:857813301292:web:7b9acad0f822973f55f989',
    messagingSenderId: '857813301292',
    projectId: 'cs184-flutter-app',
    authDomain: 'cs184-flutter-app.firebaseapp.com',
    storageBucket: 'cs184-flutter-app.appspot.com',
    measurementId: 'G-YJ6PRKJ4S1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl1X8t58aM8zL9GVPc4zPxUe8iwusoNco',
    appId: '1:857813301292:android:ce15c7db1af235cb55f989',
    messagingSenderId: '857813301292',
    projectId: 'cs184-flutter-app',
    storageBucket: 'cs184-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy_ZCbuYSrFGn5w6B4yOG8-umQRIzrZOI',
    appId: '1:857813301292:ios:7621bd585047d06455f989',
    messagingSenderId: '857813301292',
    projectId: 'cs184-flutter-app',
    storageBucket: 'cs184-flutter-app.appspot.com',
    iosBundleId: 'com.example.helloWorld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy_ZCbuYSrFGn5w6B4yOG8-umQRIzrZOI',
    appId: '1:857813301292:ios:116ee7a5581f08be55f989',
    messagingSenderId: '857813301292',
    projectId: 'cs184-flutter-app',
    storageBucket: 'cs184-flutter-app.appspot.com',
    iosBundleId: 'com.example.helloWorld.RunnerTests',
  );
}
